/*
 * FormLogin.java
 *
 * Created on 17 de abril de 2008, 11:24 AM
 */

package presentacion;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Stack;
import java.util.StringTokenizer;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import negocio.FileUtil;
import negocio.cliente.ControlCliente;


/**
 *
 * @author  timo
 */
public class FormLogin extends javax.swing.JDialog implements ActionListener{
    public static final int OK = 0;
    public static final int CANCEL = 1;
    
    int value = CANCEL;
    String user = "";
    Stack yaUsados;
    /** Creates new form FormLogin */
    public FormLogin(java.awt.Frame parent, boolean modal ,String usados) {
        super(parent, modal);
        initComponents();
        cargarUsados( usados );
        cargarImgs();
        setLocationRelativeTo( null );
        setSize( 400 , 400 );
    }
    
    public int showDialog(){
        super.show();
        return value;
    }
    
    public String getResult(){
        return user;
    }
    
    public void cargarImgs( ){
        
        for (int i = 1; i < 30; i++) {
            if( yaUsados.search( i+"" ) == -1 ){
                JButton btn = new JButton();
                btn.setActionCommand( i+"" );
                btn.setIcon( getImage( i+".png" ) );
                btn.addActionListener( this );
                panelImgs.add( btn );
            }
        }
    }    
    
    private void cargarUsados( String str ){
        yaUsados = new Stack();
        StringTokenizer stoken = new StringTokenizer( str );
        String temp;
        while( stoken.hasMoreTokens() ){
            temp = stoken.nextToken();
            temp = temp.substring( 0 , temp.indexOf('#') );
            yaUsados.push( temp );
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        panelImgs = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Iniciar sesi\u00f3n");
        panelImgs.setLayout(new java.awt.GridLayout(5, 2, 3, 10));

        jScrollPane1.setViewportView(panelImgs);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin(new javax.swing.JFrame(), true).setVisible(true);
            }
        });*/
    }
    
    public void actionPerformed(ActionEvent e) {
        
        if( e.getSource() instanceof JButton ){
            value = OK;
            user = e.getActionCommand();
            dispose();
        }
    }
    
    private ImageIcon getImage(String string) {
        return new ImageIcon( getClass().getResource("/images/ids/" + string ));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelImgs;
    // End of variables declaration//GEN-END:variables
    
    
}
